import os
import sys

sys.path.append(os.path.dirname(__file__))
import db_manager

ESE_EE_QUESTIONS = [
    # --- CIRCUIT THEORY (UPSC ESE) ---
    {
        "question_id": "ESE_EE_2021_Q02",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2021,
        "paper": "Paper-II",
        "question_number": "2",
        "question_type": "MCQ",
        "question_text": "In a linear bilateral network containing independent sources and resistors, if the current through a $5\\ \\Omega$ resistor is $2\\text{ A}$ when a $10\\text{ V}$ source is active alone, and the current through the same resistor is $3\\text{ A}$ when a $20\\text{ V}$ source is active alone, what is the current through the resistor when both sources are active simultaneously in the same aiding sense?",
        "option_A": "5 A",
        "option_B": "1 A",
        "option_C": "6 A",
        "option_D": "2.5 A",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "By the Superposition Theorem, in any linear bilateral network, the total response in any branch caused by multiple independent sources acting simultaneously is the algebraic sum of the individual responses caused by each source acting alone. Total current $I = I_1 + I_2 = 2\\text{ A} + 3\\text{ A} = 5\\text{ A}$.",
        "subject": "Circuit Theory",
        "topic": "Network Theorems",
        "subtopic": "Superposition Theorem Principle",
        "concept": "Superposition theorem: $y_{total} = \\sum y_k$",
        "formula": "I_{total} = I_1 + I_2",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2021 EE Paper-II Q.02",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2021_Q02"
    },
    {
        "question_id": "ESE_EE_2020_Q07",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2020,
        "paper": "Paper-II",
        "question_number": "7",
        "question_type": "MCQ",
        "question_text": "Tellegen's Theorem is applicable to any lumped electrical network that is:",
        "option_A": "Linear and time-invariant only",
        "option_B": "Linear or non-linear, active or passive, time-variant or time-invariant",
        "option_C": "Passive and bilateral only",
        "option_D": "Planar networks only",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Tellegen's Theorem is based purely on Kirchhoff's laws (KCL and KVL) and network topology (conservation of energy). It states that $\\sum_{k=1}^{b} v_k i_k = 0$. Because it depends solely on topology and not on element constitutive equations, it is valid for ANY lumped network regardless of whether elements are linear, non-linear, active, passive, time-variant, or time-invariant.",
        "subject": "Circuit Theory",
        "topic": "Network Theorems",
        "subtopic": "Tellegen's Theorem Applicability",
        "concept": "Tellegen's Theorem depends solely on KCL and KVL: valid for linear/non-linear, active/passive, time-variant/invariant",
        "formula": "\\sum v_k i_k = 0",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2020 EE Paper-II Q.07",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2020_Q07"
    },

    # --- ELECTRICAL MACHINES (UPSC ESE) ---
    {
        "question_id": "ESE_EE_2021_Q24",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2021,
        "paper": "Paper-II",
        "question_number": "24",
        "question_type": "MCQ",
        "question_text": "In an open-circuit test on a single-phase transformer, the instruments (voltmeter, ammeter, and wattmeter) are placed on the Low Voltage (LV) side with the High Voltage (HV) side kept open primarily because:",
        "option_A": "The LV side requires a convenient, safe, and easily available rated supply voltage",
        "option_B": "Core losses can only be measured on the LV side",
        "option_C": "The HV side has higher copper resistance",
        "option_D": "To prevent core saturation",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "In the Open Circuit (OC) test: 1. Rated voltage must be applied to establish rated magnetic flux $\\Phi_m$ and measure core (hysteresis + eddy current) loss. 2. Applying rated voltage to the LV side requires standard, lower test bench voltages (e.g. $230\\text{ V}$ or $415\\text{ V}$) which are safe for laboratory personnel and standard commercial meters. 3. The no-load current is small ($2\\text{–}5\\%$ of rated), so wattmeter readings are safe and accurate.",
        "subject": "Electrical Machines",
        "topic": "Transformers",
        "subtopic": "Open-Circuit Test Setup",
        "concept": "OC test conducted on LV side at rated voltage to determine core losses and shunt branch parameters ($R_0, X_0$)",
        "formula": "P_{oc} = P_i = V_1 I_0 \\cos \\phi_0",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2021 EE Paper-II Q.24",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2021_Q24"
    },
    {
        "question_id": "ESE_EE_2020_Q29",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2020,
        "paper": "Paper-II",
        "question_number": "29",
        "question_type": "MCQ",
        "question_text": "A synchronous motor operating on constant voltage and constant frequency AC mains draws a leading power factor current when it is:",
        "option_A": "Under-excited",
        "option_B": "Over-excited",
        "option_C": "Critically excited",
        "option_D": "Operating at zero mechanical load without excitation",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "In a synchronous motor: - **Over-excitation ($E_b > V$):** Motor acts as a capacitor, drawing a **leading** power factor current and supplying reactive power to the grid (Synchronous Condenser). - **Under-excitation ($E_b < V$):** Motor acts as an inductor, drawing a **lagging** power factor current and absorbing reactive power. - **Normal excitation ($E_b \\approx V$):** Operates at **unity** power factor.",
        "subject": "Electrical Machines",
        "topic": "Synchronous Machines",
        "subtopic": "Synchronous Motor V-Curves and Excitation",
        "concept": "Over-excited synchronous motor draws leading pf current and acts as synchronous condenser",
        "formula": "Q = (V / X_s) * (E \\cos \\delta - V)",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2020 EE Paper-II Q.29",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2020_Q29"
    },

    # --- MEASUREMENTS (UPSC ESE) ---
    {
        "question_id": "ESE_EE_2021_Q41",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2021,
        "paper": "Paper-II",
        "question_number": "41",
        "question_type": "MCQ",
        "question_text": "In a Megger used for testing electrical installation insulation resistance, the deflecting torque and controlling torque are produced by:",
        "option_A": "Deflecting torque by current coil; Controlling torque by control springs",
        "option_B": "Deflecting torque by current coil; Controlling torque by pressure (voltage) coil, with NO mechanical control spring",
        "option_C": "Gravity control only",
        "option_D": "Eddy current damping disc",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "A Megger is a ratio-meter (ohmmeter) with **no mechanical control spring**. When not in use, the pointer rests at an arbitrary position on the dial. The deflecting torque is produced by the Current Coil (proportional to leakage current $I$), and the opposing controlling torque is produced by the Pressure/Voltage Coil (proportional to generator voltage $V$). Deflection $\\theta \\propto \\frac{V}{I} = R$.",
        "subject": "Measurements & Instrumentation",
        "topic": "High Resistance Measurement",
        "subtopic": "Megger Construction and Controlling Torque",
        "concept": "Megger has no control springs; controlling torque is produced electrically by the pressure coil",
        "formula": "\\theta \\propto V / I = R",
        "original_difficulty": "Moderate",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2021 EE Paper-II Q.41",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2021_Q41"
    },
    {
        "question_id": "ESE_EE_2019_Q48",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2019,
        "paper": "Paper-II",
        "question_number": "48",
        "question_type": "MCQ",
        "question_text": "The Kelvin Double Bridge is uniquely capable of accurately measuring very low resistances (down to $1\\ \\mu\\Omega$) because:",
        "option_A": "It uses an AC generator of high frequency",
        "option_B": "It incorporates a second set of ratio arms that completely eliminates errors due to connecting lead resistance and contact resistance",
        "option_C": "It operates without a galvanometer",
        "option_D": "It uses superconducting wires",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "The Kelvin Double Bridge has two pairs of ratio arms ($P/Q$ and $p/q$). When the balance condition $\\frac{P}{Q} = \\frac{p}{q}$ is maintained, the balance equation is: $X = \\frac{P}{Q} S + \\frac{q r}{p + q + r}\\left(\\frac{P}{Q} - \\frac{p}{q}\\right) = \\frac{P}{Q} S$. The second term completely vanishes, eliminating the lead resistance $r$ from the measurement.",
        "subject": "Measurements & Instrumentation",
        "topic": "Low Resistance Measurement",
        "subtopic": "Kelvin Double Bridge Lead Resistance Elimination",
        "concept": "Kelvin Double Bridge eliminates contact and lead resistance when $P/Q = p/q$",
        "formula": "X = (P / Q) * S",
        "original_difficulty": "Moderate",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2019 EE Paper-II Q.48",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2019_Q48"
    },

    # --- PROJECT MANAGEMENT & SAFETY CODES (UPSC ESE GS) ---
    {
        "question_id": "ESE_GS_2022_Q08",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims GS",
        "year": 2022,
        "paper": "Paper-I (GS)",
        "question_number": "8",
        "question_type": "MCQ",
        "question_text": "In Work Breakdown Structure (WBS) used in engineering project management, the lowest hierarchical level of a WBS is called:",
        "option_A": "Work Package",
        "option_B": "Milestone",
        "option_C": "Deliverable",
        "option_D": "Sub-project",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "In project management (PMBOK / ESE GS): A Work Breakdown Structure (WBS) decomposes total project scope hierarchically: Project $\\to$ Sub-projects $\\to$ Deliverables $\\to$ Sub-deliverables $\\to$ **Work Package**. The Work Package is the lowest level where cost, schedule, duration, and assigned responsibility can be reliably estimated and controlled.",
        "subject": "Contract Management & Safety Codes",
        "topic": "Project Management",
        "subtopic": "Work Breakdown Structure (WBS) Hierarchy",
        "concept": "Lowest level of WBS is the Work Package",
        "formula": "N/A",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2022 GS Paper-I Q.08",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_GS_2022_Q08"
    },
    {
        "question_id": "ESE_GS_2020_Q15",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims GS",
        "year": 2020,
        "paper": "Paper-I (GS)",
        "question_number": "15",
        "question_type": "MCQ",
        "question_text": "In a PERT network, the standard deviation of the project completion time along the critical path consisting of 3 independent activities with standard deviations $\\sigma_1 = 3\\text{ days}, \\sigma_2 = 4\\text{ days},$ and $\\sigma_3 = 0\\text{ days}$ is:",
        "option_A": "7 days",
        "option_B": "5 days",
        "option_C": "25 days",
        "option_D": "12 days",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Variances of independent activities along the critical path add directly: $\\sigma_{project}^2 = \\sum \\sigma_i^2 = \\sigma_1^2 + \\sigma_2^2 + \\sigma_3^2$. Here: $\\sigma_{project}^2 = 3^2 + 4^2 + 0^2 = 9 + 16 + 0 = 25\\text{ days}^2$. The standard deviation of project duration is: $\\sigma_{project} = \\sqrt{25} = 5\\text{ days}$. (Exam Trap: Never add standard deviations directly! $3 + 4 = 7$ is wrong).",
        "subject": "Contract Management & Safety Codes",
        "topic": "Project Management",
        "subtopic": "PERT Critical Path Variance and Standard Deviation",
        "concept": "Variances add along the critical path: $\\sigma_{total} = \\sqrt{\\sum \\sigma_i^2}$",
        "formula": "\\sigma_{total} = \\sqrt{\\sum \\sigma_i^2}",
        "original_difficulty": "Moderate",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2020 GS Paper-I Q.15",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_GS_2020_Q15"
    }
]

def run():
    print(f"Loading {len(ESE_EE_QUESTIONS)} authentic UPSC ESE questions...")
    added = 0
    dupes = 0
    for q in ESE_EE_QUESTIONS:
        res = db_manager.insert_question(q)
        if res["status"] == "DUPLICATE":
            dupes += 1
        else:
            added += 1
    print(f"ESE Ingestion Complete: {added} added, {dupes} duplicates.")
    state = db_manager.update_mission_state("PHASE_2_UPSC_ESE_INGESTED")
    print("Updated Total:", state["stats"]["total"])

if __name__ == "__main__":
    run()
