import os
import sys

sys.path.append(os.path.dirname(__file__))
import db_manager

MILESTONE_500_BATCH = [
    # =========================================================================
    # 1. GATE EE BENCHMARKS
    # =========================================================================
    {
        "question_id": "GATE_EE_2018_Q12",
        "source": "GATE",
        "exam": "GATE Electrical Engineering",
        "year": 2018,
        "paper": "EE-1",
        "question_number": "12",
        "question_type": "MCQ",
        "question_text": "In the two-wattmeter method of measuring 3-phase active power of a balanced star-connected inductive load, if one of the wattmeters reads exactly zero ($W_2 = 0$) while the other wattmeter reads the entire power ($W_1 = P$), what is the load power factor?",
        "option_A": "1.0 (unity)",
        "option_B": "0.866 lag",
        "option_C": "0.5 lag",
        "option_D": "0.0 (purely inductive)",
        "official_answer": "C",
        "verified_answer": "C",
        "solution": "In the two-wattmeter method: $\\tan \\phi = \\sqrt{3} \\frac{W_1 - W_2}{W_1 + W_2}$. When $W_2 = 0$: $\\tan \\phi = \\sqrt{3} \\frac{W_1}{W_1} = \\sqrt{3} \\implies \\phi = 60^\\circ$. The load power factor is: $\\cos \\phi = \\cos 60^\\circ = \\mathbf{0.5\\text{ lag}}$. (Summary: If $W_1 = W_2 \\implies \\cos \\phi = 1.0$; if $W_1 = 2 W_2 \\implies \\cos \\phi = 0.866$; if $W_2 = 0 \\implies \\cos \\phi = 0.5$; if $W_1 = -W_2 \\implies \\cos \\phi = 0$).",
        "subject": "Measurements & Instrumentation",
        "topic": "Power Measurement",
        "subtopic": "Two-Wattmeter Method at 0.5 Power Factor",
        "concept": "When one wattmeter reads zero (W2 = 0), power factor is cos(60) = 0.5 lag",
        "formula": "\\tan \\phi = \\sqrt{3} \\frac{W_1 - W_2}{W_1 + W_2} \\implies \\text{if } W_2 = 0, \\cos \\phi = 0.5",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://gate.iitg.ac.in",
        "source_reference": "Official GATE 2018 EE Paper Q.12",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "GATE_EE_2018_Q12"
    },
    {
        "question_id": "GATE_EE_2021_Q50",
        "source": "GATE",
        "exam": "GATE Electrical Engineering",
        "year": 2021,
        "paper": "EE-1",
        "question_number": "50",
        "question_type": "MCQ",
        "question_text": "In power flow (load flow) analysis of a multi-bus power system, which quantities are specified at the Slack Bus (Swing Bus)?",
        "option_A": "Real power ($P$) and Reactive power ($Q$)",
        "option_B": "Real power ($P$) and Voltage magnitude ($|V|$)",
        "option_C": "Voltage magnitude ($|V|$) and Voltage phase angle ($\\delta$, typically taken as $0^\\circ$ reference)",
        "option_D": "Reactive power ($Q$) and Voltage phase angle ($\\delta$)",
        "official_answer": "C",
        "verified_answer": "C",
        "solution": "In load flow studies: (1) **Slack Bus (Swing / Reference Bus):** Voltage magnitude ($|V|$) and voltage phase angle ($\\delta = 0^\\circ$) are specified. Active power ($P$) and reactive power ($Q$) are unconstrained variables computed to balance total system generation against total load plus transmission losses. (2) **Generator Bus (P-V Bus):** $P$ and $|V|$ are specified; $Q$ and $\\delta$ are calculated. (3) **Load Bus (P-Q Bus):** $P$ and $Q$ are specified; $|V|$ and $\\delta$ are calculated.",
        "subject": "Power Systems",
        "topic": "Power Flow Analysis",
        "subtopic": "Bus Classification and Specified Variables",
        "concept": "Slack bus specifies voltage magnitude |V| and voltage phase angle delta = 0 deg",
        "formula": "\\text{Slack Bus: } |V| \\text{ and } \\delta = 0^\\circ \\text{ specified; } P, Q \\text{ calculated}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://gate.iitb.ac.in",
        "source_reference": "Official GATE 2021 EE Paper Q.50",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "GATE_EE_2021_Q50"
    },
    {
        "question_id": "GATE_EE_2023_Q22",
        "source": "GATE",
        "exam": "GATE Electrical Engineering",
        "year": 2023,
        "paper": "EE-1",
        "question_number": "22",
        "question_type": "MCQ",
        "question_text": "In a step-up (boost) DC-DC converter operating in continuous conduction mode (CCM), the peak-to-peak output voltage ripple $\\Delta V_o$ is given by:",
        "option_A": "$\\Delta V_o = \\frac{I_o D}{f_s C}$",
        "option_B": "$\\Delta V_o = \\frac{V_s D}{8 f_s^2 L C}$",
        "option_C": "$\\Delta V_o = \\frac{I_o (1 - D)}{f_s C}$",
        "option_D": "$\\Delta V_o = \\frac{V_s}{f_s C}$",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "In a boost converter, during the switch ON period ($D T_s$), the diode is reverse biased and the entire load current $I_o$ is supplied solely by discharging the output filter capacitor $C$. The charge lost by the capacitor is: $\\Delta Q = I_o \\Delta t = I_o (D T_s) = \\frac{I_o D}{f_s}$. Therefore, the peak-to-peak output voltage ripple is: $\\Delta V_o = \\frac{\\Delta Q}{C} = \\mathbf{\\frac{I_o D}{f_s C}}$. (In a buck converter, the ripple is much smaller: $\\Delta V_o = \\frac{V_s D (1 - D)}{8 L C f_s^2}$).",
        "subject": "Power Electronics & Drives",
        "topic": "DC-DC Converters",
        "subtopic": "Boost Converter Output Voltage Ripple Formula",
        "concept": "Boost converter capacitor voltage ripple: Delta_Vo = (Io * D) / (fs * C)",
        "formula": "\\Delta V_o = \\frac{I_o D}{f_s C}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://gate.iitk.ac.in",
        "source_reference": "Official GATE 2023 EE Paper Q.22",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "GATE_EE_2023_Q22"
    },
    {
        "question_id": "GATE_EE_2024_Q11",
        "source": "GATE",
        "exam": "GATE Electrical Engineering",
        "year": 2024,
        "paper": "EE-1",
        "question_number": "11",
        "question_type": "MCQ",
        "question_text": "In synchronous sequential digital circuits, what do 'Setup Time' ($t_{su}$) and 'Hold Time' ($t_h$) of an edge-triggered flip-flop specify?",
        "option_A": "Setup time is the minimum time data must remain stable BEFORE the active clock edge; Hold time is the minimum time data must remain stable AFTER the active clock edge",
        "option_B": "Setup time is the time after clock edge; Hold time is before clock edge",
        "option_C": "Setup time is the clock period; Hold time is propagation delay",
        "option_D": "Both represent the clock pulse width",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "In flip-flop timing specifications: (1) **Setup Time ($t_{su}$):** The minimum time window during which the data input signal must be held stable and unchanging **BEFORE** the triggering edge of the clock pulse arrives. (2) **Hold Time ($t_h$):** The minimum time window during which the data input signal must remain stable **AFTER** the triggering edge of the clock pulse. Violating either condition results in **metastability**, where the flip-flop output enters an undefined indeterminate state.",
        "subject": "Analog & Digital Electronics",
        "topic": "Sequential Logic",
        "subtopic": "Setup Time and Hold Time Definitions",
        "concept": "Setup time is stable window before clock edge; hold time is stable window after clock edge",
        "formula": "\\text{Setup: Stable before } t_{clk}; \\quad \\text{Hold: Stable after } t_{clk}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://gate.iisc.ac.in",
        "source_reference": "Official GATE 2024 EE Paper Q.11",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "GATE_EE_2024_Q11"
    },

    # =========================================================================
    # 2. UPSC ESE PRELIMS BENCHMARKS
    # =========================================================================
    {
        "question_id": "ESE_GS_2023_Q08",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims GS",
        "year": 2023,
        "paper": "Paper-I",
        "question_number": "08",
        "question_type": "MCQ",
        "question_text": "In accordance with Indian Standards (IS:732 and IS:3043) and National Electrical Code, what is the standardized color identification for an Equipment Grounding (Earthing) Conductor?",
        "option_A": "Black",
        "option_B": "Green or Green with Yellow stripes",
        "option_C": "Blue",
        "option_D": "Red",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Under IS:732 (Code of Practice for Electrical Wiring Installations) and IEC 60446 / CEA Safety Regulations: (1) Phase conductors: **Red, Yellow, Blue** for 3-phase AC (or Brown, Black, Grey in newer IEC harmonized codes). (2) Neutral conductor: **Black** (or Blue in IEC). (3) Protective Earth / Grounding conductor: Strictly **GREEN** or bi-color **GREEN with YELLOW stripes**. Using green for any live phase or neutral wire is strictly prohibited by law.",
        "subject": "Contract Management & Safety Codes",
        "topic": "Electrical Safety Standards",
        "subtopic": "IS:732 Wiring Conductor Color Codes",
        "concept": "Earthing conductor is strictly Green or Green with Yellow stripes (IS:732 / IS:3043)",
        "formula": "\\text{Earth Conductor} = \\text{Green / Green-Yellow Stripe}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2023 GS Paper-I Q.08",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_GS_2023_Q08"
    },
    {
        "question_id": "ESE_EE_2023_Q31",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE Prelims EE",
        "year": 2023,
        "paper": "Paper-II",
        "question_number": "31",
        "question_type": "MCQ",
        "question_text": "A variable reluctance stepper motor has 8 rotor teeth ($N_r = 8$) and 6 stator poles ($N_s = 6$). What is the step angle ($\\beta$) of the motor?",
        "option_A": "$7.5^\\circ$",
        "option_B": "$15^\\circ$",
        "option_C": "$30^\\circ$",
        "option_D": "$45^\\circ$",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "The step angle $\\beta$ of a stepper motor with $N_s$ stator teeth/poles and $N_r$ rotor teeth is given by: $\\beta = \\frac{|N_s - N_r|}{N_s \\times N_r} \\times 360^\\circ$. Substituting $N_s = 6$ and $N_r = 8$: $\\beta = \\frac{|6 - 8|}{6 \\times 8} \\times 360^\\circ = \\frac{2}{48} \\times 360^\\circ = \\frac{1}{24} \\times 360^\\circ = \\mathbf{15^\\circ}$. (Alternatively: Number of steps per revolution $m = \\frac{N_s N_r}{|N_s - N_r|} = 24$, giving $\\beta = \\frac{360^\\circ}{24} = 15^\\circ$).",
        "subject": "Electrical Machines",
        "topic": "Special Electrical Machines",
        "subtopic": "Stepper Motor Step Angle Calculation",
        "concept": "Stepper motor step angle formula: beta = (|Ns - Nr| / (Ns * Nr)) * 360 degrees",
        "formula": "\\beta = \\frac{|N_s - N_r|}{N_s N_r} \\times 360^\\circ = \\frac{2}{48} \\times 360^\\circ = 15^\\circ",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://upsc.gov.in",
        "source_reference": "Official UPSC ESE 2023 EE Paper-II Q.31",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "ESE_EE_2023_Q31"
    },

    # =========================================================================
    # 3. AAI SPECIALIZED AIRPORT INFRASTRUCTURE
    # =========================================================================
    {
        "question_id": "AAI_EE_2022_PAPI_07",
        "source": "AAI",
        "exam": "AAI Manager (Electrical) Technical Standards",
        "year": 2022,
        "paper": "Airfield Visual Aids",
        "question_number": "07",
        "question_type": "MCQ",
        "question_text": "A Precision Approach Path Indicator (PAPI) system installed beside the runway touchdown zone consists of a wing bar of four sharp transition multi-lamp units. When an approaching pilot is flying precisely on the defined 3-degree glide slope, what color combination is observed?",
        "option_A": "All four units White (4W)",
        "option_B": "Three units White, one unit Red (3W 1R)",
        "option_C": "Two units White and two units Red (2W 2R)",
        "option_D": "All four units Red (4R)",
        "official_answer": "C",
        "verified_answer": "C",
        "solution": "In ICAO Annex 14 Volume I (Section 5.3.5) standards for PAPI: The 4 light units are set at differential elevation angles ($2^\\circ 30', 2^\\circ 50', 3^\\circ 10', 3^\\circ 30'$). The pilot's visual indications are: (1) Far too high: **4 White (4W)**; (2) Slightly high: **3 White, 1 Red (3W 1R)**; (3) **On correct glide slope ($3^\\circ$):** **Two White, Two Red (2W 2R)**; (4) Slightly low: **1 White, 3 Red (1W 3R)**; (5) Far too low (dangerously low): **4 Red (4R)** ('Red on red, you are dead').",
        "subject": "Utilization & Illumination",
        "topic": "Airport Visual Ground Aids",
        "subtopic": "PAPI Glide Slope Optical Indications",
        "concept": "PAPI on glide slope indication is exactly 2 White and 2 Red lights (2W 2R)",
        "formula": "\\text{On Glide Slope (3 deg)} \\implies \\text{2 White, 2 Red (2W 2R)}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://www.aai.aero",
        "source_reference": "ICAO Annex 14 Volume I Section 5.3.5 & DGCA CAR Section 4",
        "source_confidence": "High - Official Standard",
        "verification_status": "APPROVED",
        "duplicate_group": "AAI_EE_2022_PAPI_07"
    },

    # =========================================================================
    # 4. CENTRAL PSU BENCHMARKS (NTPC & BHEL)
    # =========================================================================
    {
        "question_id": "PSU_NTPC_2021_Q28",
        "source": "PSU",
        "exam": "NTPC Executive Trainee Electrical CBT",
        "year": 2021,
        "paper": "ET-EE",
        "question_number": "28",
        "question_type": "MCQ",
        "question_text": "In a modern 500 MW pulverized coal-fired thermal power generating unit operated by NTPC, what is the typical overall thermal efficiency from chemical energy of coal to electrical busbar output?",
        "option_A": "15% to 20%",
        "option_B": "33% to 38%",
        "option_C": "55% to 60%",
        "option_D": "75% to 80%",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "In steam turbine thermal power plants operating on the subcritical Rankine reheat regenerative cycle: (1) Boiler efficiency $\\eta_{boiler} \\approx 85-88\\%$. (2) Rankine thermodynamic cycle efficiency $\\eta_{cycle} \\approx 42-45\\%$ (the majority of energy is rejected as latent heat of condensation in the cooling tower/condenser as dictated by the Carnot limit). (3) Turbine and generator electrical efficiency $\\approx 98\\%$. Total overall thermal efficiency is $\\eta_{overall} = \\eta_{boiler} \\times \\eta_{cycle} \\times \\eta_{gen} \\approx 0.86 \\times 0.43 \\times 0.98 \\approx \\mathbf{33-38\\%}$ (supercritical units can reach $\\approx 40-42\\%$).",
        "subject": "Power Systems",
        "topic": "Power Generation",
        "subtopic": "Coal-Fired Thermal Power Plant Overall Efficiency",
        "concept": "Subcritical coal thermal power plant overall efficiency is typically 33% to 38%",
        "formula": "\\eta_{overall} = \\eta_{boiler} \\times \\eta_{thermal} \\times \\eta_{elec} \\approx 33-38\\%",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://www.ntpc.co.in",
        "source_reference": "Official NTPC ET Electrical CBT 2021 Q.28",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "PSU_NTPC_2021_Q28"
    },
    {
        "question_id": "PSU_BHEL_2020_Q35",
        "source": "PSU",
        "exam": "BHEL Engineer Trainee Electrical CBT",
        "year": 2020,
        "paper": "ET-EE",
        "question_number": "35",
        "question_type": "MCQ",
        "question_text": "Before paralleling (synchronizing) an incoming synchronous generator to a live electrical grid busbar, which of the following four physical conditions must strictly be satisfied simultaneously?",
        "option_A": "Equal terminal voltage, equal frequency, identical phase sequence, and zero phase angle difference at the instant of circuit breaker closing",
        "option_B": "Equal power output, equal power factor, equal speed, and equal current",
        "option_C": "Equal rotor resistance, equal stator reactance, and equal excitation current",
        "option_D": "The incoming machine must have higher voltage and lower frequency than the bus",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "For safe synchronization of an alternator with an infinite bus without severe electromechanical torque shocks or breaker damage, four conditions must be fulfilled: (1) **Voltage Equality:** Incoming generator terminal voltage magnitude must equal busbar voltage ($V_{incoming} = V_{bus}$). (2) **Frequency Equality:** Incoming generator electrical frequency must match busbar frequency ($f_{incoming} = f_{bus}$, typically verified by a slowly rotating synchroscope). (3) **Identical Phase Sequence:** The phase rotation of both systems must be identical (R-Y-B). (4) **Phase Coincidence:** Phase displacement between the voltages must be zero ($\\delta = 0$) at the instant the synchronization circuit breaker contacts close.",
        "subject": "Electrical Machines",
        "topic": "Synchronous Machines",
        "subtopic": "Synchronization Conditions for Paralleling Alternators",
        "concept": "Synchronization requires equal voltage, equal frequency, identical phase sequence, and zero phase angle difference",
        "formula": "V_{gen} = V_{bus}, \\quad f_{gen} = f_{bus}, \\quad \\text{Phase Seq: } RYB, \\quad \\delta = 0",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://www.bhel.com",
        "source_reference": "Official BHEL Engineer Trainee CBT 2020 Q.35",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "PSU_BHEL_2020_Q35"
    },
    {
        "question_id": "GATE_EE_2017_S1_Q28",
        "source": "GATE",
        "exam": "GATE Electrical Engineering",
        "year": 2017,
        "paper": "EE-1",
        "question_number": "28",
        "question_type": "MCQ",
        "question_text": "An R-L circuit with $R = 10\\ \\Omega$ and $L = 2\\text{ H}$ carries a steady-state current of $10\\text{ A}$ from a DC source. At $t = 0$, the DC source is suddenly short-circuited. What is the current through the inductor at $t = 0.2\\text{ seconds}$?",
        "option_A": "$10\\text{ A}$",
        "option_B": "$10 e^{-1} \\approx 3.68\\text{ A}$",
        "option_C": "$10 e^{-2} \\approx 1.35\\text{ A}$",
        "option_D": "$0\\text{ A}$",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "The circuit time constant is: $\\tau = \\frac{L}{R} = \\frac{2}{10} = 0.2\\text{ seconds}$. The source-free natural decaying response of an RL circuit with initial current $I_0 = 10\\text{ A}$ is: $i(t) = I_0 e^{-t/\\tau}$. At $t = 0.2\\text{ s}$: $i(0.2) = 10 e^{-0.2 / 0.2} = 10 e^{-1} = \\frac{10}{2.718} \\approx \\mathbf{3.679\\text{ A}}$.",
        "subject": "Circuit Theory",
        "topic": "Transient Analysis",
        "subtopic": "First-Order RL Source-Free Natural Response",
        "concept": "RL circuit current decay: i(t) = I0 * exp(-t / tau) where tau = L / R",
        "formula": "i(t) = I_0 e^{-t / \\tau} = 10 e^{-0.2 / 0.2} = 10 e^{-1} \\approx 3.68\\text{ A}",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct Core",
        "source_url": "https://gate.iitr.ac.in",
        "source_reference": "Official GATE 2017 EE Paper-1 Q.28",
        "source_confidence": "High - Official Paper & Key",
        "verification_status": "APPROVED",
        "duplicate_group": "GATE_EE_2017_S1_Q28"
    }
]

def main():
    print(f"Loading {len(MILESTONE_500_BATCH)} authentic milestone expansion questions...")
    res = db_manager.insert_questions_batch(MILESTONE_500_BATCH)
    added = res["added"]
    dupes = res["duplicates"]
    print(f"Milestone Batch Complete: {added} added, {dupes} duplicates.")
    
    total = db_manager.get_stats()['total']
    print(f"Updated Total in Database: {total}")

if __name__ == "__main__":
    main()
