import sys
import os

# Ensure database path is available
sys.path.append(os.path.dirname(__file__))
from db_manager import insert_question, init_db

questions_batch1_partB = [
    # =========================================================================
    # MPU-05: Memory interfacing & I/O interfacing (Memory mapped vs I/O mapped) (3 questions)
    # =========================================================================
    {
        "question_id": "GATE-EE-2018-MPU-Q04",
        "source": "GATE",
        "exam": "GATE EE",
        "year": 2018,
        "paper": "EE",
        "question_number": "Q31",
        "question_type": "MCQ",
        "question_text": "In microprocessor-based system design, what is a fundamental difference between Memory-Mapped I/O and Peripheral-Mapped (I/O Mapped / Isolated) I/O?",
        "option_A": "Memory-mapped I/O uses 8-bit device addresses, while I/O-mapped uses 16-bit addresses",
        "option_B": "Memory-mapped I/O allows any memory-reference instruction (e.g. MOV, ADD, CMP) to manipulate I/O ports, whereas I/O-mapped requires dedicated IN and OUT instructions",
        "option_C": "Memory-mapped I/O has faster execution time and consumes no memory address space",
        "option_D": "I/O-mapped scheme generates MEMR' and MEMW' control signals",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "In Memory-Mapped I/O, I/O ports are treated as memory locations with 16-bit addresses, allowing all memory-referencing instructions (MOV, LDA, STA, ADD M) to access ports directly, though it reduces available RAM/ROM memory address space. In I/O-Mapped I/O, ports have separate 8-bit addresses (00H to FFH) accessed exclusively via IN and OUT instructions with IOR' and IOW' control signals.",
        "subject": "Microprocessors & Microcomputers",
        "topic": "Microprocessors & Microcomputers",
        "subtopic": "Memory & I/O Interfacing [MPU-05]",
        "concept": "Memory-Mapped vs Peripheral-Mapped I/O [MPU-05]",
        "formula": "Memory-Mapped: 16-bit address (MEMR'/MEMW'); Isolated: 8-bit address (IOR'/IOW')",
        "original_difficulty": "Medium",
        "AAI_relevance": "High",
        "source_reference": "GATE EE 2018 & Gaonkar Microprocessors",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ESE-EE-2022-MPU-Q05",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2022,
        "paper": "EE-Paper-1",
        "question_number": "Q68",
        "question_type": "MCQ",
        "question_text": "A 3-to-8 line decoder (such as 74LS138) is used to decode the higher-order address lines A15, A14, and A13 in an 8085 memory interface. If output Y3' (active LOW) is connected to the Chip Select (CS') pin of an 8 KB EPROM, what is the assigned address range of this EPROM?",
        "option_A": "0000H to 1FFFH",
        "option_B": "6000H to 7FFFH",
        "option_C": "4000H to 5FFFH",
        "option_D": "8000H to 9FFFH",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "An 8 KB memory has 8192 locations, requiring 13 address lines (A0 to A12, 2¹³ = 8192). The higher 3 lines (A15, A14, A13) feed the 3-to-8 decoder. Output Y3' is activated when (A15 A14 A13) = (0 1 1)_2 = 3. Address ranges from: A15-A13 = 011, with A12-A0 = 0 0000 0000 0000 to 1 1111 1111 1111 => Binary 0110 0000 0000 0000 (6000H) to 0111 1111 1111 1111 (7FFFH).",
        "subject": "Microprocessors & Microcomputers",
        "topic": "Microprocessors & Microcomputers",
        "subtopic": "Memory & I/O Interfacing [MPU-05]",
        "concept": "Address Decoding with 74LS138 [MPU-05]",
        "formula": "Range = 011_0000_0000_0000 (6000H) to 011_1111_1111_1111 (7FFFH)",
        "original_difficulty": "Medium",
        "AAI_relevance": "Direct",
        "source_reference": "UPSC ESE EE 2022 & Gaonkar",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ISRO-EE-2020-MPU-Q06",
        "source": "ISRO",
        "exam": "ISRO Scientist/Engineer",
        "year": 2020,
        "paper": "EE",
        "question_number": "Q49",
        "question_type": "MCQ",
        "question_text": "In interfacing slow peripheral devices or slow EPROMs to an 8085 microprocessor, which hardware pin is sampled during the T2 state to insert Wait states (Tw)?",
        "option_A": "HOLD",
        "option_B": "READY",
        "option_C": "INTR",
        "option_D": "RESET IN'",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "The READY input pin is used to synchronize the 8085 with slow memory or peripheral devices. The microprocessor tests the READY pin during T2 state. If READY is LOW (not ready), the CPU enters an idle Wait state (Tw) until READY goes HIGH, thereby extending the read/write bus cycle without dropping data.",
        "subject": "Microprocessors & Microcomputers",
        "topic": "Microprocessors & Microcomputers",
        "subtopic": "Memory & I/O Interfacing [MPU-05]",
        "concept": "READY Pin and Wait State Generation [MPU-05]",
        "formula": "If READY = 0 at T2 => Insert Wait States (Tw)",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "ISRO Scientist EE 2020 & Gaonkar",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },

    # =========================================================================
    # PEL-02: Power Electronics: Triggering, commutation, snubber (3 questions)
    # =========================================================================
    {
        "question_id": "GATE-EE-2021-PEL-Q01",
        "source": "GATE",
        "exam": "GATE EE",
        "year": 2021,
        "paper": "EE",
        "question_number": "Q25",
        "question_type": "MCQ",
        "question_text": "In a Silicon Controlled Rectifier (SCR) circuit, what is the precise distinction between Latching Current (I_L) and Holding Current (I_H)?",
        "option_A": "I_L is associated with turn-off and is always smaller than I_H",
        "option_B": "I_L is the minimum anode current required to maintain turn-on after gate pulse removal, and is typically 2 to 3 times greater than I_H",
        "option_C": "I_H is the minimum current required to trigger the gate, while I_L is leakage current",
        "option_D": "Both currents are identical in magnitude and function",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Latching current (I_L) is the minimum anode current that the SCR must attain at the time of turn-on so that it remains in the conduction state even after the gate pulse is removed (associated with turn-on). Holding current (I_H) is the minimum anode current below which the SCR drops out of conduction back to forward blocking (associated with turn-off). For any standard thyristor, I_L is approximately 2 to 3 times I_H (I_L > I_H).",
        "subject": "Power Electronics & Drives",
        "topic": "Power Electronics and Drives",
        "subtopic": "SCR Characteristics & Ratings [PEL-02]",
        "concept": "Latching Current vs Holding Current [PEL-02]",
        "formula": "I_L ≈ (2 to 3) * I_H",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "GATE EE 2021 & Power Electronics by P.S. Bimbhra",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ESE-EE-2020-PEL-Q02",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2020,
        "paper": "EE-Paper-2",
        "question_number": "Q34",
        "question_type": "MCQ",
        "question_text": "To protect a thyristor against high rate of rise of voltage (dv/dt) and high rate of rise of current (di/dt), which protection components are connected to the SCR?",
        "option_A": "An inductor in parallel with the SCR for dv/dt, and a capacitor in series for di/dt",
        "option_B": "A series inductor (L) for di/dt protection, and an RC snubber circuit connected in parallel across the SCR for dv/dt protection",
        "option_C": "A zener diode in series and a fuse in parallel",
        "option_D": "A shunt resistor for di/dt and series capacitor for dv/dt",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Inductors oppose sudden changes in current (v = L di/dt); thus, an inductor in series with the SCR limits di/dt to safe levels. Capacitors oppose sudden changes in voltage (i = C dv/dt); thus, an RC snubber circuit connected in parallel across the SCR bypasses high-frequency voltage transients and limits dv/dt.",
        "subject": "Power Electronics & Drives",
        "topic": "Power Electronics and Drives",
        "subtopic": "SCR Protection Circuits [PEL-02]",
        "concept": "di/dt and dv/dt Protection [PEL-02]",
        "formula": "Series L limits di/dt; Parallel RC snubber limits dv/dt",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "UPSC ESE EE 2020 & Bimbhra",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ESE-EE-2019-PEL-Q03",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2019,
        "paper": "EE-Paper-2",
        "question_number": "Q41",
        "question_type": "MCQ",
        "question_text": "In a UJT relaxation oscillator used for thyristor gate firing, the intrinsic standoff ratio η = 0.63. If the supply voltage V_BB = 20 V and the emitter-base forward diode drop V_D = 0.7 V, what is the peak firing voltage V_P of the UJT?",
        "option_A": "13.3 V",
        "option_B": "12.6 V",
        "option_C": "19.3 V",
        "option_D": "7.4 V",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "The peak triggering voltage of a UJT is given by: V_P = η * V_BB + V_D. Given η = 0.63, V_BB = 20 V, V_D = 0.7 V. V_P = 0.63 * 20 + 0.7 = 12.6 + 0.7 = 13.3 V.",
        "subject": "Power Electronics & Drives",
        "topic": "Power Electronics and Drives",
        "subtopic": "Thyristor Firing Circuits [PEL-02]",
        "concept": "UJT Peak Firing Voltage Calculation [PEL-02]",
        "formula": "V_P = eta * V_BB + V_D",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "UPSC ESE EE 2019 & Rashid Power Electronics",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },

    # =========================================================================
    # PMP-01: Pumps & Water lifting devices, classification (3 questions)
    # =========================================================================
    {
        "question_id": "ESE-ME-2020-PMP-Q01",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2020,
        "paper": "ME/EE-Allied",
        "question_number": "Q18",
        "question_type": "MCQ",
        "question_text": "What fundamental hydraulic characteristic distinguishes Positive Displacement pumps (e.g. reciprocating, gear, peristaltic) from Rotodynamic (centrifugal) pumps?",
        "option_A": "Positive displacement pumps deliver a pulsating discharge practically independent of discharge pressure/head, whereas centrifugal discharge drops significantly as discharge head increases",
        "option_B": "Centrifugal pumps cannot pump water",
        "option_C": "Positive displacement pumps have lower discharge pressure limits than centrifugal pumps",
        "option_D": "Positive displacement pumps require continuous priming, while centrifugal pumps never require priming",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "Positive displacement pumps trap a fixed volume of liquid and physically displace it into the discharge line per stroke/revolution, delivering an approximately constant flow rate regardless of pressure (nearly vertical Q-H curve). In contrast, centrifugal pumps impart kinetic energy via a rotating impeller, causing flow rate to decrease continuously as head increases (drooping Q-H curve).",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "Classification of Pumps [PMP-01]",
        "concept": "Positive Displacement vs Rotodynamic Characteristics [PMP-01]",
        "formula": "Positive displacement: Q ≈ constant; Centrifugal: H vs Q droops",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "UPSC ESE ME/Fluid Mechanics by Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "STATE-AE-2021-PMP-Q02",
        "source": "STATE_AE",
        "exam": "State AE Mechanical/Electrical",
        "year": 2021,
        "paper": "Fluid-Machinery",
        "question_number": "Q22",
        "question_type": "MCQ",
        "question_text": "For draining stormwater and airport apron dewatering with high discharge capacity at relatively low head (Head < 5 meters), which type of rotodynamic pump is most suitable?",
        "option_A": "Multistage centrifugal pump",
        "option_B": "Axial flow (propeller) pump",
        "option_C": "Reciprocating plunger pump",
        "option_D": "Gear pump",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Axial flow (propeller) pumps operate at high specific speeds (Ns > 9000 US units / 160 SI units) and are ideally suited for moving large volumes of liquid at low total dynamic heads (< 5-7 m), making them the standard choice for drainage, stormwater lift stations, and flood dewatering.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "Classification of Pumps [PMP-01]",
        "concept": "Axial Flow Pump Application Criteria [PMP-01]",
        "formula": "Axial flow: High Q, Low H, High Specific Speed Ns",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "Modi & Seth Fluid Mechanics & Hydraulic Machinery",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "CPWD-MEP-2022-PMP-Q03",
        "source": "MEP_CODES",
        "exam": "CPWD Specifications for Water Supply",
        "year": 2022,
        "paper": "Sanitary-Pumps",
        "question_number": "Q09",
        "question_type": "MCQ",
        "question_text": "Why must a centrifugal pump never be started against an open discharge valve when pumping into an empty pipe network, whereas a positive displacement pump must NEVER be started against a closed discharge valve?",
        "option_A": "Centrifugal starting power is zero; Positive displacement creates cavitation",
        "option_B": "Centrifugal pump motor can overload on open delivery due to excessive flow (runout), while a positive displacement pump creates catastrophic overpressure that ruptures piping or burns the motor if the discharge is shut",
        "option_C": "Centrifugal impellers rotate backwards if started closed",
        "option_D": "Both pumps can be started in any valve position without restriction",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "A centrifugal pump has minimum shaft power at zero flow (shut-off head), making closed-valve starting normal practice to prevent motor overload. A positive displacement pump displaces fluid positively with every stroke; starting against a closed valve causes pressure to rise instantaneously until pipe rupture, pump body fracture, or motor trip occurs, necessitating an integral safety pressure relief valve.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "Classification of Pumps [PMP-01]",
        "concept": "Centrifugal vs Positive Displacement Starting Rules [PMP-01]",
        "formula": "Centrifugal: Min power at shut-off (Q=0); Positive Displacement: P -> infinity at Q=0",
        "original_difficulty": "Medium",
        "AAI_relevance": "High",
        "source_reference": "CPWD Works Manual & Hydraulic Institute Standards",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },

    # =========================================================================
    # PMP-03: NPSH (Net Positive Suction Head), Cavitation causes (3 questions)
    # =========================================================================
    {
        "question_id": "GATE-ME-2019-PMP-Q01",
        "source": "GATE",
        "exam": "GATE ME/Fluid Machinery",
        "year": 2019,
        "paper": "ME",
        "question_number": "Q35",
        "question_type": "MCQ",
        "question_text": "A centrifugal pump is installed above a water sump. The atmospheric pressure is 10.3 m of water, water vapor pressure is 0.3 m of water, suction lift hs = 3.0 m, and suction pipe friction loss hfs = 1.0 m. What is the Net Positive Suction Head Available (NPSHA) at the pump suction flange?",
        "option_A": "6.0 m",
        "option_B": "7.0 m",
        "option_C": "8.0 m",
        "option_D": "5.0 m",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "NPSHA is given by: NPSHA = (Patm / γ) - hs - hfs - (Pv / γ). Here Patm/γ = 10.3 m, hs = 3.0 m, hfs = 1.0 m, Pv/γ = 0.3 m. NPSHA = 10.3 - 3.0 - 1.0 - 0.3 = 6.0 m.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "NPSH & Cavitation [PMP-03]",
        "concept": "Calculation of NPSH Available [PMP-03]",
        "formula": "NPSHA = (Patm / gamma) - hs - hfs - (Pv / gamma)",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "GATE ME 2019 & Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ESE-EE-2022-PMP-Q02",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2022,
        "paper": "General-Engg",
        "question_number": "Q44",
        "question_type": "MCQ",
        "question_text": "Cavitation in a centrifugal pump occurs when the absolute pressure at the eye of the impeller drops below:",
        "option_A": "Atmospheric pressure",
        "option_B": "Vapor pressure of the liquid at operating temperature",
        "option_C": "Critical pressure of water",
        "option_D": "Zero gauge pressure",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Cavitation begins when the local static pressure inside the pump (most commonly at the suction eye of the impeller) drops to or below the saturation vapor pressure (Pv) of the liquid at the flowing temperature, causing vapor bubbles to flash. As these bubbles travel into higher pressure regions, they violently collapse, causing severe pitting, noise, vibration, and drop in efficiency.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "NPSH & Cavitation [PMP-03]",
        "concept": "Cavitation Phenomenon Criteria [PMP-03]",
        "formula": "Cavitation occurs when P_local <= P_vapor",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "UPSC ESE & Fluid Mechanics by Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "STATE-AE-2023-PMP-Q03",
        "source": "STATE_AE",
        "exam": "State AE Mechanical/Electrical",
        "year": 2023,
        "paper": "Paper-2",
        "question_number": "Q29",
        "question_type": "MCQ",
        "question_text": "Thoma's cavitation factor σ is defined in terms of Net Positive Suction Head (NPSH) and Total Manometric Head (H) as:",
        "option_A": "σ = NPSH / H",
        "option_B": "σ = H / NPSH",
        "option_C": "σ = NPSH * H",
        "option_D": "σ = sqrt(NPSH / H)",
        "official_answer": "A",
        "verified_answer": "A",
        "solution": "Thoma's cavitation factor (or cavitation parameter) σ is a non-dimensional ratio defined as σ = NPSH / H, where NPSH is the net positive suction head and H is the total manometric head of the pump (or effective head for turbines). Cavitation is prevented as long as σ > σ_critical.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "PUMPS",
        "subtopic": "NPSH & Cavitation [PMP-03]",
        "concept": "Thoma's Cavitation Factor [PMP-03]",
        "formula": "sigma = NPSH / H",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "Modi & Seth Fluid Mechanics",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },

    # =========================================================================
    # PMP-05: Dimensional analysis & similitude (Reynolds, Froude numbers) (3 questions)
    # =========================================================================
    {
        "question_id": "GATE-ME-2020-PMP-Q04",
        "source": "GATE",
        "exam": "GATE ME/CE",
        "year": 2020,
        "paper": "ME",
        "question_number": "Q22",
        "question_type": "MCQ",
        "question_text": "In dimensional analysis, the ratio of inertia force to viscous force is represented by which dimensionless number, and what is its standard mathematical definition?",
        "option_A": "Froude Number = v / sqrt(g * L)",
        "option_B": "Reynolds Number = (rho * v * L) / mu",
        "option_C": "Weber Number = (rho * v² * L) / sigma",
        "option_D": "Euler Number = v / sqrt(p / rho)",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Reynolds number (Re) represents the ratio of inertia force to viscous force: Re = (Inertia force) / (Viscous force) = (rho * v * L) / mu = (v * L) / nu. It is the governing similitude parameter for closed conduit pipe flow and fully submerged body flows.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "HYDRAULICS AND FLUID MECHANICS",
        "subtopic": "Dimensional Analysis & Similitude [PMP-05]",
        "concept": "Reynolds Number Definition [PMP-05]",
        "formula": "Re = (rho * v * D) / mu = Inertia Force / Viscous Force",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "GATE ME 2020 & Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "ESE-CE-2021-PMP-Q05",
        "source": "UPSC_ESE",
        "exam": "UPSC ESE",
        "year": 2021,
        "paper": "General-Engg",
        "question_number": "Q36",
        "question_type": "MCQ",
        "question_text": "In the design of open airport stormwater drainage canals, spillways, and hydraulic jumps where gravity force predominates over viscous force, which model law must be satisfied for dynamic similarity?",
        "option_A": "Reynolds Model Law",
        "option_B": "Froude Model Law (Fr_model = Fr_prototype)",
        "option_C": "Mach Model Law",
        "option_D": "Weber Model Law",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Where gravity forces dominate fluid flow with a free surface (such as open channels, weirs, stormwater drains, and hydraulic jumps), Froude's model law governs dynamic similitude: Fr = v / sqrt(g * L), requiring Fr_model = Fr_prototype.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "HYDRAULICS AND FLUID MECHANICS",
        "subtopic": "Dimensional Analysis & Similitude [PMP-05]",
        "concept": "Froude Model Law for Open Channels [PMP-05]",
        "formula": "Fr = v / sqrt(g * y); Fr_m = Fr_p",
        "original_difficulty": "Easy",
        "AAI_relevance": "High",
        "source_reference": "UPSC ESE & Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    },
    {
        "question_id": "GATE-CE-2021-PMP-Q06",
        "source": "GATE",
        "exam": "GATE CE/ME",
        "year": 2021,
        "paper": "Fluid-Mech",
        "question_number": "Q17",
        "question_type": "MCQ",
        "question_text": "According to Buckingham's Pi theorem, if a physical fluid problem involves n variables and m fundamental primary dimensions (M, L, T), how many independent dimensionless Pi-groups are formed?",
        "option_A": "n * m",
        "option_B": "n - m",
        "option_C": "n + m",
        "option_D": "m / n",
        "official_answer": "B",
        "verified_answer": "B",
        "solution": "Buckingham's Pi theorem states that if there are n total physical variables involved in a dimensionally homogeneous equation, and these variables contain m primary fundamental dimensions (e.g. Mass M, Length L, Time T), the equation can be expressed in terms of (n - m) independent dimensionless Pi-terms.",
        "subject": "Pumps & Fluid Mechanics",
        "topic": "HYDRAULICS AND FLUID MECHANICS",
        "subtopic": "Dimensional Analysis & Similitude [PMP-05]",
        "concept": "Buckingham Pi Theorem [PMP-05]",
        "formula": "Number of Pi terms = n - m",
        "original_difficulty": "Easy",
        "AAI_relevance": "Direct",
        "source_reference": "GATE CE 2021 & Modi & Seth",
        "source_confidence": "HIGH",
        "verification_status": "APPROVED"
    }
]

def main():
    init_db()
    added = 0
    skipped = 0
    print(f"Starting ingestion of Batch 1 Part B ({len(questions_batch1_partB)} questions)...")
    for q in questions_batch1_partB:
        res = insert_question(q)
        if res.get("status") == "DUPLICATE":
            skipped += 1
        else:
            added += 1
    print(f"Batch 1 Part B Ingestion Summary:")
    print(f" - Added: {added}")
    print(f" - Skipped: {skipped}")

if __name__ == "__main__":
    main()
